### ISSUE TITLE
Wrong approval check for Mooniswap

### ISSUE THREAD

**Issue by nonseodion** [DePayFi/depay-evm-router#1]
In [DePayV1ProcessorBeta.concatinated.sol ](https://github.com/DePayFi/ethereum-contracts/blob/master/contracts/DePayV1ProcessorBeta.concatinated.sol) and [DePayV1ProcessorBeta.sol](https://github.com/DePayFi/ethereum-contracts/blob/master/contracts/DePayV1ProcessorBeta.sol) the `swapOnMooniswap` function checks for approval of `UniswapV2Router` before performing a swap on `Mooniswap`. The check should be done on the `Mooniswap` contract.

```
function swapOnMooniswap(address[] memory path, uint amountIn, uint amountOut) private {
        
        if( 
            path[0] != ZERO &&
            ERC20(path[0]).allowance(address(this), UniswapV2Router02) < amountIn
        ) {
            ERC20(path[0]).approve(Mooniswap, MAXINT);
        }
```

**Comment by spape** [comment]
Will be addressed as soon as we rewrite the mooniswap router for v1.
